### PR TITLE
Basic UI of Creating Listing Form

### PR DESCRIPTION
**Pull request by NathanCarriere**
Another PR into a feature branch. Basically another progress update. 

Just the basic UI. This is without much design consideration... styling is yet to be done. Haven't cleaned the code up much yet. I tested the character limits and they seem to work. 

image

### CODE REVIEW

**Review by Mik3Qiao — APPROVED** [review]
Looks good, Better if the dialog is made bigger

**Review by AzizulHakim96 — COMMENTED** [review]
So, If someone misses any details will there be anything printing on the screen? (Not sure if its a frontend part or not)

**Review by AzizulHakim96 — APPROVED** [review]

**Review by RonnieDsouza — COMMENTED** [review]
Is it too early to add the other fields that Mike requested? 

1. ~~number of bedrooms (String)~~
2. ~~number of washrooms (String)~~
3. price (String)
4. laundryroom (boolean)
5. Pet is allowed or not  (boolean)
6. ~~description (String)~~
7. ~~title (String)~~
8. image(String)
9. parking (boolean)

**Comment by RonnieDsouza** [comment]
Could you update the screenshot please! And maybe also add an additional screenshot of the whole screen if possible.
I think it's good tho!

**Pull request merged**
